version: '3.8'
services:
  mediamtx:
    image: bluenviron/mediamtx:1
    ports:
      - "8554:8554"    # RTSP
      - "8888:8888"    # HTTP
      - "8890:8890"    # SRT
      - "9997:9997"    # API
      - "10001:10001/udp"  # UDP input for channel1
      - "10002:10002/udp"  # UDP inputs continued
      - "10003:10003/udp"
      - "10004:10004/udp"
      - "10005:10005/udp"
      - "10006:10006/udp"
      - "10007:10007/udp"
      - "10008:10008/udp"
      - "10009:10009/udp"
      - "10010:10010/udp"
      - "10011:10011/udp"
      - "10012:10012/udp"
      - "10013:10013/udp"
      - "10014:10014/udp"
      - "10015:10015/udp"
      - "10016:10016/udp"
      - "10017:10017/udp"
      - "10018:10018/udp"
      - "10019:10019/udp"
      - "10020:10020/udp"
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml
#    command: -config /mediamtx.yml